import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Path from '../components/Path';
import OneMoreFriend from '../components/SubBanner/OneMoreFriend';;
import { PetCard } from '../components/BuyPet/PetCard';
import Pagination from '@mui/material/Pagination';
import DogsFilter from '../components/Filter/DogsFilter';
import axios from 'axios';

const Category = () => {
    const [params, setParams] = useState({ min: '0', max: '100000', page: 1 });
    const [dogs, setDogs] = useState([]);
    const [totalDogs, setTotalDogs] = useState(10);
    useEffect(() => {
        handleSearch();
    }, [params]);
    const handleSearch = async () => {
        if (isNaN(params.min) || params.min.trim() === '') params.min = '0';
        if (isNaN(params.max) || params.max.trim() == '') params.max = '1000000';
        const res1 = await axios.get('http://localhost:8080/dogs/getNumber', {
            params,
            withCredentials: 'true',
        });
        setTotalDogs(res1.data.numberDogs);
        const res = await axios.get('http://localhost:8080/dogs/search', {
            params,
            withCredentials: 'true',
        });
        console.log(res);
        setDogs(res.data);
    };
    useEffect(() => {
        window.scrollTo(0, 0);
    }, [params.page]);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="">
                <Path />
                <OneMoreFriend className="mt-3" />
                <div className="grid tablet:grid-cols-4 w-full gap-5">
                    <DogsFilter params={params} setParams={setParams} />
                    <div className="tablet:col-span-3">
                        <div className="flex w-full h-[85px]   flex-col justify-start tablet:justify-between tablet:items-center tablet:flex-row">
                            <div className="flex items-end">
                                <p className="leading-8 text-[24px] font-bold text-[#003459] capitalize">
                                    {params.breed || 'Total'} dogs
                                </p>
                                <p className="text-14-20-500 text-[#667479] ml-[14px] mb-1 ">
                                    {totalDogs} pupples
                                </p>
                            </div>
                        </div>
                        <div className="grid grid-cols-2 laptop:grid-cols-3 gap-x-[28px] gap-y-5">
                            {dogs.map((dog) => (
                                <PetCard dog={dog} />
                            ))}
                        </div>

                        <div className="w-full flex justify-center mt-10">
                            <Pagination
                                count={Math.ceil(totalDogs / 10)}
                                variant="outlined"
                                shape="rounded"
                                color="primary"
                                onChange={(e, page) => {
                                    setParams((pre) => ({ ...pre, page }));
                                }}
                            />
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};


export default Category;
