import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/Banner';
import Background from '../components/Banner/Background';
import BuyPet from '../components/BuyPet';
import OneMoreFriend from '../components/SubBanner/OneMoreFriend';
import Adoption from '../components/SubBanner/Adoption';
import PetSeller from '../components/PetSeller';
import PetKnowledge from '../components/PetKnowledge';
export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="relative">
                <Background />
                <Banner />
            </header>

            <main className="bg-white w-[100vw] -ml-[16px] laptop:-ml-[60px] desktop:-ml-[130px] mt-0 min-h-[1000px]">
                <div className="subMain mx-4 laptop:mx-[60px] desktop:mx-[130px]">
                    <BuyPet />
                    <OneMoreFriend className="mt-[60px]" />
                    <PetSeller />
                    <Adoption />
                    <PetKnowledge />
                </div>
            </main>
        </div>
    );
}
