import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import PetContent from '../../components/PetDetail/PetContent';

const Pet = () => {
    const router = useRouter();
    const [dog, setDog] = useState({});
    useEffect(() => {
        const { id } = router.query;
        const getDog = async () => {
            const res = await axios.get('http://localhost:8080/dog', { params: { id } });
            setDog(res.data);
        };
        getDog();
    }, [router]);
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <PetContent dog={dog} />
            </main>
        </div>
    );
};

export default Pet;
